# Generated by Django 4.2.5 on 2023-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_university_options_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': '专业', 'verbose_name_plural': '专业'},
        ),
    ]
