# Generated by Django 4.2.5 on 2023-12-01 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_category_alter_post_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='专业代码'),
        ),
        migrations.CreateModel(
            name='MajorUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.major', verbose_name='专业')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university', verbose_name='大学')),
            ],
        ),
    ]
