# Generated by Django 4.2.5 on 2023-12-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_major_major_id_majoruniversity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='university_id',
        ),
        migrations.AddField(
            model_name='major',
            name='school',
            field=models.CharField(default=0, max_length=16, verbose_name='学院名称'),
            preserve_default=False,
        ),
    ]
