# Generated by Django 4.2.5 on 2023-12-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_majoruniversity_options_major_english_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majoruniversity',
            old_name='major_id',
            new_name='major',
        ),
    ]
