# Generated by Django 4.2.5 on 2023-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_major_id_majoruniversity_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='major',
            name='major_type',
            field=models.SmallIntegerField(choices=[(1, '经济学'), (2, '理学'), (3, '工学'), (4, '教育学'), (5, '管理学'), (6, '文学'), (7, '历史学'), (8, '哲学'), (9, '法学'), (10, '艺术学'), (11, '医学')], default=3, verbose_name='专业类别'),
            preserve_default=False,
        ),
    ]
