# Generated by Django 4.2.5 on 2023-12-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_options_major_major_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmitInformation',
            new_name='AdmitInfo',
        ),
    ]
