# Generated by Django 4.2.5 on 2023-12-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_admitinfo_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='english_exam',
        ),
        migrations.RemoveField(
            model_name='major',
            name='politic_exam',
        ),
        migrations.RemoveField(
            model_name='major',
            name='professional_exam1',
        ),
        migrations.RemoveField(
            model_name='major',
            name='professional_exam2',
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_exam1', models.CharField(max_length=16, verbose_name='专业课1')),
                ('professional_exam2', models.CharField(max_length=16, verbose_name='专业课2')),
                ('english_exam', models.CharField(max_length=16, verbose_name='英语')),
                ('politic_exam', models.CharField(max_length=16, verbose_name='政治')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.major')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目',
            },
        ),
    ]
