# Generated by Django 4.2.5 on 2023-12-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_major_english_exam_remove_major_politic_exam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitinfo',
            options={'verbose_name': '录取信息', 'verbose_name_plural': '录取信息'},
        ),
        migrations.AlterField(
            model_name='admitinfo',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总分'),
        ),
    ]
