# Generated by Django 4.2.5 on 2023-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_admitinfo_options_alter_admitinfo_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitinfo',
            name='score2',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='复试分数'),
        ),
        migrations.AlterField(
            model_name='admitinfo',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总分'),
        ),
    ]
