# Generated by Django 4.2.5 on 2023-12-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_admitinfo_score2_alter_admitinfo_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='media/images'),
        ),
    ]
