# Generated by Django 4.2.5 on 2023-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='app/media/images/'),
        ),
    ]
