# Generated by Django 4.2.5 on 2023-12-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_notice_owner_id_alter_notice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
