# Generated by Django 4.2.5 on 2023-12-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_notice_commenter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=32, verbose_name='通知内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='通知创建时间')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
