# Generated by Django 4.2.5 on 2023-12-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_notification_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
            options={
                'verbose_name': '帖子-关键词',
                'verbose_name_plural': '帖子-关键词',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='commenter_id',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='notify',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.notification'),
        ),
        migrations.AddField(
            model_name='notify',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
