# Generated by Django 4.2.5 on 2023-12-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notify_tagpost_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='是否是新的通知'),
        ),
    ]
