# Generated by Django 4.2.5 on 2023-12-06 12:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_likenotification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentnotification',
            options={'verbose_name': '评论通知', 'verbose_name_plural': '评论通知'},
        ),
        migrations.AlterModelOptions(
            name='likenotification',
            options={'verbose_name': '点赞通知', 'verbose_name_plural': '点赞通知'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='草稿标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True, verbose_name='草稿正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='帖子创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='帖子作者')),
            ],
            options={
                'verbose_name': '草稿',
                'verbose_name_plural': '草稿',
            },
        ),
    ]
