# Generated by Django 4.2.5 on 2023-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_commentnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='帖子创建时间'),
        ),
    ]
