# Generated by Django 4.2.5 on 2023-12-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_draft_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='university',
            name='phone',
        ),
        migrations.AddField(
            model_name='university',
            name='info',
            field=models.CharField(default=123456, max_length=32, verbose_name='联系方式'),
            preserve_default=False,
        ),
    ]
