# Generated by Django 4.2.5 on 2023-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_university_mail_remove_university_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitinfo',
            name='rank',
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(default='static/img/buaa.png', upload_to='static/img/', verbose_name='校徽'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_tag',
            field=models.SmallIntegerField(choices=[(0, '普通高校'), (1, '211'), (2, '985, 211')], default=0, verbose_name='学校标签'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='media/images/', verbose_name='头像'),
        ),
    ]
