# Generated by Django 4.2.5 on 2023-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_admitinfo_rank_university_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_type',
            field=models.SmallIntegerField(choices=[(1, '哲学'), (2, '经济学'), (3, '法学'), (4, '教育学'), (5, '文学'), (6, '历史学'), (7, '理学'), (8, '工学'), (9, '农学'), (10, '医学'), (11, '军事学'), (12, '管理学'), (13, '艺术学'), (14, '交叉学科')], verbose_name='专业类别'),
        ),
    ]
