# Generated by Django 4.2.5 on 2023-12-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_major_major_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='school',
        ),
        migrations.AddField(
            model_name='majoruniversity',
            name='school',
            field=models.CharField(default=1, max_length=16, verbose_name='学院名称'),
            preserve_default=False,
        ),
    ]
