# Generated by Django 4.2.5 on 2023-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_major_school_majoruniversity_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=32, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='majoruniversity',
            name='school',
            field=models.CharField(max_length=64, verbose_name='学院名称'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=32, verbose_name='学校名字'),
        ),
    ]
